version: '3.7'

include:
  - compose-files/auth-api.yaml
  - compose-files/pokemon-api.yaml

services:
  gateway:
    image: nginx:1.27.2-alpine
    volumes:
      - ./server-configs/:/etc/nginx/conf.d/:ro
      - ./auth-setup-server.conf:/etc/nginx/auth-setup-server.conf:ro
      - ./auth-setup-http.conf:/etc/nginx/auth-setup-http.conf:ro
      - ./docs-override.conf:/etc/nginx/docs-override.conf:ro
    ports:
      - "8081:80"
    networks:
      - pokedex-gamba-net
    depends_on:
      - auth-api
      - pokemon-api

networks:
  pokedex-gamba-net:
