version: '3.7'

include:
  - compose-files/auth-api.yaml
  - compose-files/pokemon-api.yaml
  - compose-files/gamba-api.yaml
  - compose-files/inventory-api.yaml
  - compose-files/trading-api.yaml

services:
  gateway:
    image: nginx:1.27.2-alpine
    volumes:
      - ./server-configs/:/etc/nginx/conf.d/:ro
      - ./auth-setup-server.conf:/etc/nginx/auth-setup-server.conf:ro
      - ./auth-setup-http.conf:/etc/nginx/auth-setup-http.conf:ro
      - ./docs-override.conf:/etc/nginx/docs-override.conf:ro
    ports:
      - "8081:80"
    networks:
      - pokedex-gamba-net
      - pokedex-gamba-gateway-public-net
    depends_on:
      - auth-api
      - pokemon-api
      - gamba-api
      - inventory-api
      - trading-api

networks:
  pokedex-gamba-net:
  pokedex-gamba-gateway-public-net:
    name: pokedex-gamba-gateway-public-net
