version: "3.7"

services:
  payment-gateway-api:
    image: ghcr.io/pokedex-gamba/payment-gateway-api:latest
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://payment-gateway-api-db:3306/payment_history
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ../grants_decoding_key:/decoding_key:ro
    networks:
      - pokedex-gamba-net
      - payment-gateway-api-db-net
    depends_on:
      - payment-gateway-api-db

  payment-gateway-api-db:
    image: ghcr.io/pokedex-gamba/payment-gateway-api-db
    build: ../services/payment-gateway-api/database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: payment_history
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - payment-gateway-api-db-data:/var/lib/mysql
    networks:
      - payment-gateway-api-db-net

volumes:
  payment-gateway-api-db-data:

networks:
  payment-gateway-api-db-net:
